import singapore from "../../../../public/images/singapore.jpg";
export const Thailand_Data = [
  {
    id: 1,
    img: singapore,
    day: "30 days",
    title: "thialind",
    name: "thialind Tourist Visa",
    lis: "thialind Immigration Fees",
    lis2: "Visa Service Charges",
    list3: "All Taxes",
    list4: "Tourist Visa",
    list5: "30 Days Duration of stay in thialind",
    list6: "60 Days Validity (Travel Time )",
    price: "USD 160",
  },
  {
    id: 2,
    img: singapore,
    day: "30 days",
    title: "thialind",
    name: "thialind Tourist Visa",
    lis: "thialind Immigration Fees",
    lis2: "Visa Service Charges",
    list3: "All Taxes",
    list4: "Tourist Visa",
    list5: "30 Days Duration of stay in thialind",
    list6: "60 Days Validity (Travel Time )",
    price: "USD 160",
  },
  {
    id: 3,
    img: singapore,
    day: "30 days",
    title: "thialind",
    name: "thialind Tourist Visa",
    lis: "thialind Immigration Fees",
    lis2: "Visa Service Charges",
    list3: "All Taxes",
    list4: "Tourist Visa",
    list5: "30 Days Duration of stay in thialind",
    list6: "60 Days Validity (Travel Time )",
    price: "USD 160",
  },
];
