export const Malaysia_Data = [
  {
    id: 1,
    day: "30 days",
    title: "malaysia",
    name: "malaysia Tourist Visa",
    lis: "malaysia Immigration Fees",
    lis2: "Visa Service Charges",
    list3: "All Taxes",
    list4: "Tourist Visa",
    list5: "30 Days Duration of stay in malaysia",
    list6: "60 Days Validity (Travel Time )",
    price: "USD 160",
  },
  {
    id: 2,
    day: "30 days",
    title: "malaysia",
    name: "malaysia Tourist Visa",
    lis: "malaysia Immigration Fees",
    lis2: "Visa Service Charges",
    list3: "All Taxes",
    list4: "Tourist Visa",
    list5: "30 Days Duration of stay in malaysia",
    list6: "60 Days Validity (Travel Time )",
    price: "USD 160",
  },
  {
    id: 3,
    day: "30 days",
    title: "malaysia",
    name: "malaysia Tourist Visa",
    lis: "malaysia Immigration Fees",
    lis2: "Visa Service Charges",
    list3: "All Taxes",
    list4: "Tourist Visa",
    list5: "30 Days Duration of stay in malaysia",
    list6: "60 Days Validity (Travel Time )",
    price: "USD 160",
  },
];
