import dubai from "../../../../public/images/dubai.jpg";
import like from "../../../../public/images/like.png"
import singapore from "../../../../public/images/singapore.jpg";
import thailand from "../../../../public/images/thailand.jpg";
import malysia from "../../../../public/images/malysia.jpg";
export const popularcard = [
    {
        id: 1,
        img: dubai,
        title: "Dubai",
        day: "30 days",
        name: "UAE Tourist Visa",
        lis: "UAE Immigration Fees",
        lis2: "Visa Service Charges",
        list3: "All Taxes",
        list4: "Tourist Visa",
        list5: "30 Days Duration of stay in UAE",
        list6: "60 Days Validity (Travel Time )",
        price: "USD 160",
        like: like,
        subCards: [
            {
                id: 101,
                img: dubai,
                title: "Dubai",
                day: "60 days",
                name: "UAE Tourist Visa",
                lis: "UAE Immigration Fees",
                lis2: "Visa Service Charges",
                lis3: "All Taxes",
                lis4: "Extended Tourist Visa",
                lis5: "60 Days Duration of stay in UAE",
                lis6: "90 Days Validity (Travel Time)",
                price: "USD 250",
                like: like,
            },
            {
                id: 102,
                img: dubai,
                title: "Dubai - Business Visa",
                day: "30 days",
                name: "UAE Business Visa",
                lis: "UAE Immigration Fees",
                lis2: "Visa Service Charges",
                lis3: "All Taxes",
                lis4: "Business Visa",
                lis5: "30 Days Duration of stay in UAE",
                lis6: "60 Days Validity (Travel Time)",
                price: "USD 200",
                like: like,
            },
            {
                id: 103,
                img: dubai,
                title: "Dubai - Tourist Package",
                day: "7 days",
                name: "UAE Tourist Package",
                lis: "Flight Included",
                lis2: "Hotel Stay",
                lis3: "City Tour",
                lis4: "Desert Safari",
                lis5: "7 Days Duration of stay in UAE",
                lis6: "10 Days Validity (Travel Time)",
                price: "USD 500",
                like: like,
            }
        ]


    },
    {
        id: 2,
        img: singapore,
        day: "30 days",
        title: "singapore",
        name: "Singapore Tourist Visa",
        lis: "singapore Immigration Fees",
        lis2: "Visa Service Charges",
        list3: "All Taxes",
        list4: "Tourist Visa",
        list5: "30 Days Duration of stay in singapore",
        list6: "60 Days Validity (Travel Time )",
        price: "USD 160",
        subCards: [
            {
                id: 101,
                title: "singapore",
                day: "60 days",
                name: "singapore Tourist Visa",
                lis: "singapore Immigration Fees",
                lis2: "Visa Service Charges",
                lis3: "All Taxes",
                lis4: "Extended Tourist Visa",
                lis5: "60 Days Duration of stay in singapore",
                lis6: "90 Days Validity (Travel Time)",
                price: "USD 250",
            },
            {
                id: 102,
                title: "singapore - Business Visa",
                day: "30 days",
                name: "singapore Business Visa",
                lis: "singapore Immigration Fees",
                lis2: "Visa Service Charges",
                lis3: "All Taxes",
                lis4: "Business Visa",
                lis5: "30 Days Duration of stay in singapore",
                lis6: "60 Days Validity (Travel Time)",
                price: "USD 200",
            },
            {
                id: 103,
                title: "singapore - Tourist Package",
                day: "7 days",
                name: "singapore Tourist Package",
                lis: "Flight Included",
                lis2: "Hotel Stay",
                lis3: "City Tour",
                lis4: "Desert Safari",
                lis5: "7 Days Duration of stay in singapore",
                lis6: "10 Days Validity (Travel Time)",
                price: "USD 500",
            }
        ]
    },
    {
        id: 3,
        img: thailand,
        title: "Thailand",
        day: "30 days",
        title: "thailand",
        name: "thailand Tourist Visa",
        lis: "thailand Immigration Fees",
        lis2: "Visa Service Charges",
        list3: "All Taxes",
        list4: "Tourist Visa",
        list5: "30 Days Duration of stay in thailand",
        list6: "60 Days Validity (Travel Time )",
        price: "USD 160",
        subCards: [
            {
                id: 101,
                title: "thailand",
                day: "60 days",
                name: "thailand Tourist Visa",
                lis: "thailand Immigration Fees",
                lis2: "Visa Service Charges",
                lis3: "All Taxes",
                lis4: "Extended Tourist Visa",
                lis5: "60 Days Duration of stay in thailand",
                lis6: "90 Days Validity (Travel Time)",
                price: "USD 250",
                like: like,
            },
            {
                id: 102,
                title: "thailand - Business Visa",
                day: "30 days",
                name: "thailand Business Visa",
                lis: "thailand Immigration Fees",
                lis2: "Visa Service Charges",
                lis3: "All Taxes",
                lis4: "Business Visa",
                lis5: "30 Days Duration of stay in thailand",
                lis6: "60 Days Validity (Travel Time)",
                price: "USD 200",
                like: like,
            },
            {
                id: 103,
                title: "thailand - Tourist Package",
                day: "7 days",
                name: "thailand Tourist Package",
                lis: "Flight Included",
                lis2: "Hotel Stay",
                lis3: "City Tour",
                lis4: "Desert Safari",
                lis5: "7 Days Duration of stay in thailand",
                lis6: "10 Days Validity (Travel Time)",
                price: "USD 500",
                like: like,
            }
        ]
    },
    {
        id: 4,
        img: thailand,
        title: "Balu",
        day: "30 days",
        title: "malaysia",
        name: "malaysia Tourist Visa",
        lis: "thailand Immigration Fees",
        lis2: "Visa Service Charges",
        list3: "All Taxes",
        list4: "Tourist Visa",
        list5: "30 Days Duration of stay in thailand",
        list6: "60 Days Validity (Travel Time )",
        price: "USD 160",

        subCards: [
            {
                id: 104,
                title: "malaysia",
                day: "60 days",
                name: "malaysia Tourist Visa",
                lis: "malaysia Immigration Fees",
                lis2: "Visa Service Charges",
                lis3: "All Taxes",
                lis4: "Extended Tourist Visa",
                lis5: "60 Days Duration of stay in malaysia",
                lis6: "90 Days Validity (Travel Time)",
                price: "USD 250",
                like: like,
            },
            {
                id: 102,
                title: "malaysia",
                day: "60 days",
                name: "malaysia Tourist Visa",
                lis: "malaysia Immigration Fees",
                lis2: "Visa Service Charges",
                lis3: "All Taxes",
                lis4: "Extended Tourist Visa",
                lis5: "60 Days Duration of stay in malaysia",
                lis6: "90 Days Validity (Travel Time)",
                price: "USD 250",
                like: like,
            },



        ]
    },
    {
        id: 5,
        img: singapore,
        title: "Balu",
        day: "30 days",
        name: "Balu Tourist Visa",
        lis: "Balu Immigration Fees",
        lis2: "Visa Service Charges",
        list3: "All Taxes",
        list4: "Tourist Visa",
        list5: "30 Days Duration of stay in Balu",
        list6: "60 Days Validity (Travel Time )",
        price: "USD 160",
        subCards: [
            {
                id: 104,
                title: "Balu",
                day: "60 days",
                name: "Balu Tourist Visa",
                lis: "Balu Immigration Fees",
                lis2: "Visa Service Charges",
                lis3: "All Taxes",
                lis4: "Extended Tourist Visa",
                lis5: "60 Days Duration of stay in Balu",
                lis6: "90 Days Validity (Travel Time)",
                price: "USD 250",
                like: like,
            },
            {
                id: 102,
                title: "Balu",
                day: "60 days",
                name: "Balu Tourist Visa",
                lis: "Balu Immigration Fees",
                lis2: "Visa Service Charges",
                lis3: "All Taxes",
                lis4: "Extended Tourist Visa",
                lis5: "60 Days Duration of stay in Balu",
                lis6: "90 Days Validity (Travel Time)",
                price: "USD 250",
                like: like,
            },



        ]

    },
    {
        id: 6,
        img: thailand,
        title: "Turkey",
        id: 4,
        day: "30 days",
        name: "Turkey Tourist Visa",
        lis: "Turkey Immigration Fees",
        lis2: "Visa Service Charges",
        list3: "All Taxes",
        list4: "Tourist Visa",
        list5: "30 Days Duration of stay in Turkey",
        list6: "60 Days Validity (Travel Time )",
        price: "USD 160",
        subCards: [
            {
                id: 104,
                title: "Tureky",
                day: "60 days",
                name: "Tureky Tourist Visa",
                lis: "Tureky Immigration Fees",
                lis2: "Visa Service Charges",
                lis3: "All Taxes",
                lis4: "Extended Tourist Visa",
                lis5: "60 Days Duration of stay in Tureky",
                lis6: "90 Days Validity (Travel Time)",
                price: "USD 250",
                like: like,
            },
            {
                id: 102,
                title: "Tureky",
                day: "60 days",
                name: "Tureky Tourist Visa",
                lis: "Tureky Immigration Fees",
                lis2: "Visa Service Charges",
                lis3: "All Taxes",
                lis4: "Extended Tourist Visa",
                lis5: "60 Days Duration of stay in Tureky",
                lis6: "90 Days Validity (Travel Time)",
                price: "USD 250",
                like: like,
            },



        ]
    },
];