import img2 from "../../../../../public/images/star4.jpg";
import img1 from "../../../../../public/images/star5.jpg";
import makkah_icons from "../../../../../public/images/makkah-icon.jpg";
import madinah_icon from "../../../../../public/images/madinah-icon.jpg";

export const Ramadan_Data = [
  {
    id: 1,
    img: img1,
    title: "14 Nights 3 Star Ramadan Umrah Package 2024",
    makkahday: "makkah 7 nights",
    madinaday: "madina 7 nights",
    icon: makkah_icons,
    icon2: madinah_icon,
    name: "ramada dar al faiyzeen",
    price: "PKR 184000",
    para: "(similar)",
    subday: "14 Nights",
  },
  {
    id: 2,
    img: img2,
    title: "12 Nights 3 Star Ramadan Umrah Package 2024",
    makkahday: "makkah 6 nights",
    madinaday: "madina 6 nights",
    icon: makkah_icons,
    icon2: madinah_icon,
    name: "ramada dar al faiyzeen",
    price: "PKR 184000",
    para: "(similar)",
    subday: "12 Nights",
  },
  {
    id: 3,
    img: img1,
    title: "10 Nights 3 Star Ramadan Umrah Package 2024",
    makkahday: "makkah 5 nights",
    madinaday: "madina 5 nights",
    icon: makkah_icons,
    icon2: madinah_icon,
    name: "ramada dar al faiyzeen",
    price: "PKR 184000",
    para: "(similar)",
    subday: "10 Nights",
  },
  {
    id: 1,
    img: img2,
    title: "7 Nights 3 Star Ramadan Umrah Package 2024",
    makkahday: "makkah 4 nights",
    madinaday: "madina 4 nights",
    icon: makkah_icons,
    icon2: madinah_icon,
    name: "ramada dar al faiyzeen",
    price: "PKR 184000",
    para: "(similar)",
    subday: "7 Nights",
  },
];

export const FourStar_Data = [
  {
    id: 1,
    img: img1,
    title: "14 Nights 4 Star Ramadan Umrah Package 2024",
    makkahday: "makkah 7 nights",
    madinaday: "madina 7 nights",
    icon: makkah_icons,
    icon2: madinah_icon,
    name: "ramada dar al faiyzeen",
    price: "PKR 184000",
    para: "(similar)",
    subday: "14 Nights",
  },
  {
    id: 2,
    img: img2,
    title: "12 Nights 4 Star Ramadan Umrah Package 2024",
    makkahday: "makkah 6 nights",
    madinaday: "madina 6 nights",
    icon: makkah_icons,
    icon2: madinah_icon,
    name: "ramada dar al faiyzeen",
    price: "PKR 184000",
    para: "(similar)",
    subday: "12 Nights",
  },
  {
    id: 3,
    img: img1,
    title: "10 Nights 4 Star Ramadan Umrah Package 2024",
    makkahday: "makkah 5 nights",
    madinaday: "madina 5 nights",
    icon: makkah_icons,
    icon2: madinah_icon,
    name: "ramada dar al faiyzeen",
    price: "PKR 184000",
    para: "(similar)",
    subday: "10 Nights",
  },
  {
    id: 1,
    img: img2,
    title: "7 Nights 4 Star Ramadan Umrah Packages 2024",
    makkahday: "makkah 4 nights",
    madinaday: "madina 4 nights",
    icon: makkah_icons,
    icon2: madinah_icon,
    name: "ramada dar al faiyzeen",
    price: "PKR 184000",
    para: "(similar)",
    subday: "7 Nights",
  },
];
export const FiveStar_Data = [
  {
    id: 1,
    img: img1,
    title: "14 Nights 5 Star Ramadan Umrah Package 2024",
    makkahday: "makkah 7 nights",
    madinaday: "madina 7 nights",
    icon: makkah_icons,
    icon2: madinah_icon,
    name: "ramada dar al faiyzeen",
    price: "PKR 184000",
    para: "(similar)",
    subday: "14 Nights",
  },
  {
    id: 2,
    img: img2,
    title: "12 Nights 5 Star Ramadan Umrah Package 2024",
    makkahday: "makkah 6 nights",
    madinaday: "madina 6 nights",
    icon: makkah_icons,
    icon2: madinah_icon,
    name: "ramada dar al faiyzeen",
    price: "PKR 184000",
    para: "(similar)",
    subday: "12 Nights",
  },
  {
    id: 3,
    img: img1,
    title: "10 Nights 5 Star Ramadan Umrah Package 2024",
    makkahday: "makkah 5 nights",
    madinaday: "madina 5 nights",
    icon: makkah_icons,
    icon2: madinah_icon,
    name: "ramada dar al faiyzeen",
    price: "PKR 184000",
    para: "(similar)",
    subday: "10 Nights",
  },
  {
    id: 1,
    img: img2,
    title: "7 Nights 5 Star Ramadan Umrah Package 2024",
    makkahday: "makkah 4 nights",
    madinaday: "madina 4 nights",
    icon: makkah_icons,
    icon2: madinah_icon,
    name: "ramada dar al faiyzeen",
    price: "PKR 184000",
    para: "(similar)",
    subday: "7 Nights",
  },
];
