import makkh from "../../../../../public/images/makkah.png";
import madina from "../../../../../public/images/madina.png";
export const Economy = [
  {
    id: 1,
    makkah_name: "Mayyar Mayysar",
    madina_name: "Wesam al Madinah 04",
    makkah: makkh,
    madina: madina,
    makkah_distance: "2500m Misfalah ",
    makkh_dire: "Hijra street - shuttle",
    madina_dire: "1200m Al Ayun - shuttle",
    price: "199,600",
  },
  {
    id: 2,
    makkah_name: "Mayyar Mayysar",
    madina_name: "Wesam al Madinah 04",
    makkah: makkh,
    madina: madina,
    makkah_distance: "2500m Misfalah ",
    makkh_dire: "Hijra street - shuttle",
    madina_dire: "1200m Al Ayun - shuttle",
    price: "199,600",
  },
  {
    id: 3,
    makkah_name: "Mayyar Mayysar",
    madina_name: "Wesam al Madinah 04",
    makkah: makkh,
    madina: madina,
    makkah_distance: "2500m Misfalah ",
    makkh_dire: "Hijra street - shuttle",
    madina_dire: "1200m Al Ayun - shuttle",
    price: "199,600",
  },
  {
    id: 4,
    makkah_name: "Mayyar Mayysar",
    madina_name: "Wesam al Madinah 04",
    makkah: makkh,
    madina: madina,
    makkah_distance: "2500m Misfalah ",
    makkh_dire: "Hijra street - shuttle",
    madina_dire: "1200m Al Ayun - shuttle",
    price: "199,600",
  },
  {
    id: 5,
    makkah_name: "Mayyar Mayysar",
    madina_name: "Wesam al Madinah 04",
    makkah: makkh,
    madina: madina,
    makkah_distance: "2500m Misfalah ",
    makkh_dire: "Hijra street - shuttle",
    madina_dire: "1200m Al Ayun - shuttle",
    price: "199,600",
  },
  {
    id: 6,
    makkah_name: "Mayyar Mayysar",
    madina_name: "Wesam al Madinah 04",
    makkah: makkh,
    madina: madina,
    makkah_distance: "2500m Misfalah ",
    makkh_dire: "Hijra street - shuttle",
    madina_dire: "1200m Al Ayun - shuttle",
    price: "199,600",
  },
];
