import { Inter } from "next/font/google";
import "./globals.css";
import Footers from "@/Common_Comp/Footers";
import Navbar from "@/Common_Comp/navbar/Navbar";
import Whatsapp from "@/components/Whatsapp";
import TopBar from "@/Common_Comp/navbar/TopBar";
import { ThemeProvider } from "@/components/theme-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Umrah ",
  description: "Generated by create next app",
  // icons: {
  //   icon: ["/favicon.ico?v=4"], // Standard favicon
  //   apple: ["/favicon.png"], // Apple touch icon
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TopBar />
          <Navbar />
          {children}
          <Footers />
          <Whatsapp />
        </ThemeProvider>
      </body>
    </html>
  );
}
