
import like from "../../../../public/images/like.png";
export const Dubai_Data = [
  {
    id: 1,
    title: "Dubai",
    day: "30 days",
    name: "UAE Tourist Visa",
    lis: "UAE Immigration Fees",
    lis2: "Visa Service Charges",
    list3: "All Taxes",
    list4: "Tourist Visa",
    list5: "30 Days Duration of stay in UAE",
    list6: "60 Days Validity (Travel Time )",
    price: "USD 160",
    like: like,
  },
  {
    id: 2,
    title: "Dubai",
    day: "30 days",
    name: "UAE Tourist Visa",
    lis: "UAE Immigration Fees",
    lis2: "Visa Service Charges",
    list3: "All Taxes",
    list4: "Tourist Visa",
    list5: "30 Days Duration of stay in UAE",
    list6: "60 Days Validity (Travel Time )",
    price: "USD 160",
    like: like,
  },
  {
    id: 3,
    title: "Dubai",
    day: "30 days",
    name: "UAE Tourist Visa",
    lis: "UAE Immigration Fees",
    lis2: "Visa Service Charges",
    list3: "All Taxes",
    list4: "Tourist Visa",
    list5: "30 Days Duration of stay in UAE",
    list6: "60 Days Validity (Travel Time )",
    price: "USD 160",
    like: like,
  },
];
